name: Test Terraform Change PR Commenter

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/test-action.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan

      # Add your action here (replace with the actual usage syntax)
      - name: Run terraform-change-pr-commenter
        uses: ./ # Uses the action in this repo
        with:
          plan-file: terraform/tfplan
